version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=app
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rodrigo
      - RABBITMQ_DEFAULT_PASS=rodrigo
    ports:
      - "5672:5672"
      - "15672:15672"