version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=app
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - 5432:5432